[pytest]
testpaths = tests
ignore = tests/test_math.py
         tests/test_string.py
         tests/test_time.py
         tests/test_collections.py
         tests/test_units.py
         tests/test_module_system.py
python_files = test_*.py
python_classes = Test*
python_functions = test_*
